// export const GET_NEW_ARRIVALS = 'GET_NEW_ARRIVALS';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';
export const SHOW_ERROR_MESSAGE = 'SHOW_ERROR_MESSAGE';
